# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtSql import *
from PyQt5.QtCore import *
from PyQt5.QtWebKitWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(540, 540)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 540, 540))
        self.label.setStyleSheet("image: url(:/newPrefix/gambarawal.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.clicked.connect(self.masukapp)
        self.pushButton.setGeometry(QtCore.QRect(75, 344, 391, 90))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QT PRAY"))
        self.pushButton.setText(_translate("Form", "Mulai Aplikasi"))

    def masukapp(self):
        widget.show()
        Form.close()

import tampilan

class MenuAwal(QMainWindow):
    def __init__(self):
        super().__init__()
        self.btasbih = QPushButton("Tasbih",self)
        self.btasbih.clicked.connect(self.tasbihon)
        self.btasbih.move(200,100)
        self.btasbih.resize(150,50)
        self.btasbih.setStyleSheet("font-family: arial;font-size: 20px;font-weight: bold;")

        self.btngaji = QPushButton("Ngaji",self)
        self.btngaji.move(200,170)
        self.btngaji.resize(150,50)
        self.btngaji.setStyleSheet("font-family: arial;font-size: 20px;font-weight: bold;")
        self.btngaji.clicked.connect(self.ngajion)

        self.btdoa = QPushButton("Doa",self)
        self.btdoa.move(200,240)
        self.btdoa.resize(150,50)
        self.btdoa.setStyleSheet("font-family: arial;font-size: 20px;font-weight: bold;")
        self.btdoa.clicked.connect(self.doaon)

        self.btabout = QPushButton("About Us",self)
        self.btabout.move(200,310)
        self.btabout.resize(150,50)
        self.btabout.setStyleSheet("font-family: arial;font-size: 20px;font-weight: bold;")
        self.btabout.clicked.connect(self.abaouton)

        self.keluar = QPushButton("Keluar",self)
        self.keluar.clicked.connect(self.keluarapp)
        self.keluar.move(430,500)


    def tasbihon(self):
        widget.setFixedHeight(730)
        widget.setFixedWidth(540)
        widget.setWindowTitle("TASBIH")
        widget.setCurrentIndex(widget.currentIndex()+1)

    def ngajion(self):
        widget.setFixedHeight(540)
        widget.setFixedWidth(540)
        widget.setWindowTitle("NGAJI")
        widget.setCurrentIndex(widget.currentIndex()+2)

    def doaon(self):
        widget.setFixedHeight(540)
        widget.setFixedWidth(540)
        widget.setWindowTitle("DOA")
        widget.setCurrentIndex(widget.currentIndex()+3)

    def abaouton(self):
        widget.setFixedHeight(540)
        widget.setFixedWidth(540)
        widget.setWindowTitle("ABOUT US")
        widget.setCurrentIndex(widget.currentIndex()+4)


    def keluarapp(self):
        QMessageBox.warning(self, 'PERINGATAN', 'ANDA AKAN KELUAR APPLIKASI')
        widget.close()


class data(QWidget):
    def __init__(self):
        super().__init__()

        self.kembali = QPushButton("Quit",self)
        self.kembali.move(440,695)
        self.kembali.clicked.connect(self.kembalikan)

        self.tanggal = QLabel("",self)
        self.tanggal.resize(0,0)

        self.jam = QLabel("",self)
        self.jam.move(210,10)
        self.jam.resize(130,30)
        self.jam.setStyleSheet("font-family: arial;font-size: 30px;font-weight: bold;")

        timer = QTimer(self) 
        timer.timeout.connect(self.showTime) 
        timer.start(1000)

        reset = QPushButton("Reset",self)
        reset.clicked.connect(self.resetin)
        reset.move(410,125)

        hapus = QPushButton("Hapus",self)
        hapus.clicked.connect(self.hapusData)
        hapus.move(150,455)

        self.tambah = QPushButton("tambah",self)
        self.tambah.clicked.connect(self.tambahdata)
        self.tambah.move(300,455)

        self.inNama = QLineEdit(self)
        self.inNama.resize(270,40)
        self.inNama.move(135,180)
        self.inNama.setPlaceholderText("USERNAME")
        self.inNama.setStyleSheet("font-family: arial;font-size: 20px;font-weight: bold;")
        self.inNama.editingFinished.connect(self.match)

        tambah = QPushButton("PUSH",self)
        tambah.resize(150,150)
        tambah.setStyleSheet("font-family: arial;font-size: 20px;color: white;background-color: black;border-radius: 75; border: 1px solid black;")
        tambah.move (200,270)
        tambah.clicked.connect(self.klick)

        self.lcd = QLabel("0",self)
        self.lcd.setStyleSheet("font-family: arial;font-size: 100px;border: 2px solid black")
        self.lcd.resize(270,100)
        self.lcd.move(135,50)

        self.tableView = QTableView(self)
        self.tableView.resize(525,120)
        self.tableView.move(7.5,490)

        simpan = QPushButton("Simpan",self)
        simpan.clicked.connect(self.update)
        simpan.move(290,630)
        simpan.resize(150,50)
        simpan.setStyleSheet("font-family: arial;font-size: 20px;font-weight: bold;")


        self.pilih = QPushButton("Pilih",self)
        self.pilih.move(110,630)
        self.pilih.resize(150,50)
        self.pilih.setStyleSheet("font-family: arial;font-size: 20px;font-weight: bold;")
        self.pilih.clicked.connect(self.pilihan)

        self.buatdatabase()
        self.tampilData()
        self.tang()

        
        
    def tang(self):
        now = QDate.currentDate()
        label_tangg = now.toString(Qt.ISODate)
        self.tanggal.setText(label_tangg)

    def showTime(self): 
        current_time = QTime.currentTime() 
        label_time = current_time.toString('hh:mm:ss') 
        self.jam.setText(label_time) 

    def klick(self):
        c = self.lcd.text()
        c = int(c) + 1
        self.lcd.setText(str(c))

    def buatdatabase(self):
        self.db = QSqlDatabase.addDatabase("QSQLITE")
        self.db.setDatabaseName("tugas.db")
        self.db.open()

        self.query = QSqlQuery()

        self.query.exec_("CREATE TABLE IF NOT EXISTS data (nama VARCHAR(25), hasil INT, Jam INT,Tanggal INT )")

    def tampilData(self):
        self.model = QSqlTableModel()
        self.model.setTable("data")
        self.model.setEditStrategy(QSqlTableModel.OnManualSubmit)
        self.model.select()
        self.tableView.setModel(self.model)

    def hapusData(self):
        index = self.tableView.selectedIndexes()[0]
        nama = self.tableView.model().data(index)
        
        self.query.exec_("DELETE FROM data WHERE nama = '"+ nama +"'")
        self.tampilData()

    def tambahdata(self):
        jam = self.jam.text()
        lcd = self.lcd.text()
        nama = self.inNama.text()
        date = self.tanggal.text()

        self.query.exec_("INSERT INTO data (nama,hasil,jam,tanggal) VALUES ('"+ nama +"', "+ lcd +" , '"+ jam +"', '"+ date +"' )")

        self.inNama.setText("")
        
        self.tampilData()


    def match(self):
        self.query.exec_("SELECT nama FROM data")
        
        c = 0
        while self.query.next() and c == 0 :
            if str(self.query.value(0)) == self.inNama.text() :
                c = 1
                
                self.tambah.setEnabled(False)
            else:
                self.tambah.setEnabled(True)

    def pilihan(self):
        
        variable = self.tableView.currentIndex().row()
        index = self.model.index(variable,1)
        angka = self.model.data(index)
        self.lcd.setText(str(angka))
        
        indexnama = self.model.index(variable,0)
        nama = self.model.data(indexnama)
        self.inNama.setText(str(nama))

        self.inNama.setEnabled(False)

    def update(self):
        baru = self.lcd.text()
        waktu = self.jam.text()
        nama = self.inNama.text()
        date = self.tanggal.text()

        self.query.exec_("UPDATE data SET hasil = '"+ baru + "', jam = '"+ waktu +"', tanggal = '"+ date +"'  WHERE nama = '"+ nama +"' " )

        self.tampilData()

        self.inNama.setEnabled(True)
        self.inNama.setText("")

    def resetin(self):
        self.lcd.setText("0")

    def kembalikan(Self):
        widget.setWindowTitle("HOME")
        widget.setFixedWidth(540)
        widget.setFixedHeight(540)
        widget.setCurrentIndex(widget.currentIndex()-1)

class ngaji(QMainWindow):
    def __init__(self):
        super().__init__()
        
        self.kembali = QPushButton("Quit",self)
        self.kembali.clicked.connect(self.kembalikan)
        self.kembali.move(430,500)

        self.btyasin = QPushButton("يٰسۤ",self)
        self.btyasin.resize(150,50)
        self.btyasin.move(200,50)
        self.btyasin.setStyleSheet("font-family: arial;font-size: 35px;font-weight: bold;")
        self.btyasin.clicked.connect(self.yasin)

        self.btarrahman = QPushButton("اَلرَّحْمٰنُۙ",self)
        self.btarrahman.move(200,120)
        self.btarrahman.resize(150,50)
        self.btarrahman.setStyleSheet("font-family: arial;font-size: 35px;font-weight: bold;")
        self.btarrahman.clicked.connect(self.arrahman)

        self.btalkahfi = QPushButton("الْكَهْفِ",self)
        self.btalkahfi.move(200,190)
        self.btalkahfi.resize(150,50)
        self.btalkahfi.setStyleSheet("font-family: arial;font-size: 35px;font-weight: bold;")
        self.btalkahfi.clicked.connect(self.alkahfi)

        self.btalmulk = QPushButton("الْمُلْكُۖ",self)
        self.btalmulk.move(200,260)
        self.btalmulk.resize(150,50)
        self.btalmulk.setStyleSheet("font-family: arial;font-size: 35px;font-weight: bold;")
        self.btalmulk.clicked.connect(self.almulk)

        self.btalwaqiah = QPushButton("الْوَاقِعَةُۙ",self)
        self.btalwaqiah.move(200,330)
        self.btalwaqiah.resize(150,50)
        self.btalwaqiah.setStyleSheet("font-family: arial;font-size: 35px;font-weight: bold;")
        self.btalwaqiah.clicked.connect(self.alwaqiah)

        self.btsurat = QPushButton("114 Surat",self)
        self.btsurat.move(200,400)
        self.btsurat.resize(150,50)
        self.btsurat.setStyleSheet("font-family: arial;font-size: 30px;font-weight: bold;")
        self.btsurat.clicked.connect(self.surat)

        self.syasin = syasin()
        self.salwaqiah = salwaqiah()
        self.sarrahman = sarrahman()
        self.salkahfi = salkahfi()
        self.salmulk = salmulk()
        self.ssurat = ssurat()

    def yasin(self):
        self.syasin.yasindisplayon()
    
    def arrahman(self):
        self.sarrahman.arrahmandisplayon()

    def alkahfi(self):
        self.salkahfi.alkahfidisplayon()
    
    def almulk(self):
        self.salmulk.almulkdisplayon()

    def alwaqiah(self):
        self.salwaqiah.alwaqiahdisplayon()

    def surat(self):
        self.ssurat.suratdisplayon()

    def kembalikan(Self):
        widget.setWindowTitle("HOME")
        widget.setFixedWidth(540)
        widget.setFixedHeight(540)
        widget.setCurrentIndex(widget.currentIndex()-2)

class syasin(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setFixedWidth(1200)

        self.setWindowTitle("Surah Yasin")

        self.browser = QWebView()
        self.browser.setUrl (QUrl("https://litequran.net/yasin"))

        self.setCentralWidget(self.browser)

    def yasindisplayon(self):
        self.show()

class sarrahman(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setFixedWidth(1200)

        self.setWindowTitle("Surah Ar - Rahman")

        self.browser = QWebView()
        self.browser.setUrl (QUrl("https://litequran.net/ar-rahman"))

        self.setCentralWidget(self.browser)

    def arrahmandisplayon(self):
        self.show()

class salkahfi(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setFixedWidth(1200)

        self.setWindowTitle("Surah Al - Kahfi")

        self.browser = QWebView()
        self.browser.setUrl (QUrl("https://litequran.net/al-kahfi"))

        self.setCentralWidget(self.browser)

    def alkahfidisplayon(self):
        self.show()
        
class salmulk(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setFixedWidth(1200)

        self.setWindowTitle("Surah Al - mulk")

        self.browser = QWebView()
        self.browser.setUrl (QUrl("https://litequran.net/al-mulk"))

        self.setCentralWidget(self.browser)

    def almulkdisplayon(self):
        self.show()

class salwaqiah(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setFixedWidth(1200)

        self.setWindowTitle("Surah Al - Waqi'ah")

        self.browser = QWebView()
        self.browser.setUrl (QUrl("https://litequran.net/al-waqiah"))

        self.setCentralWidget(self.browser)

    def alwaqiahdisplayon(self):
        self.show()

class ssurat(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setFixedWidth(1200)

        self.setWindowTitle("Surat - Surat di Al-Quran")

        self.browser = QWebView()
        self.browser.setUrl (QUrl("https://litequran.net/"))

        self.setCentralWidget(self.browser)

    def suratdisplayon(self):
        self.show()

class doa(QWidget):
    def __init__(self):
        super().__init__()

        self.kembali = QPushButton("Quit",self)
        self.kembali.clicked.connect(self.kembalikan)
        self.kembali.move(430,500)

        self.bdoa1 = QPushButton("Bersyukur",self)
        self.bdoa1.move(200,100)
        self.bdoa1.resize(150,50)
        self.bdoa1.setStyleSheet("font-family: arial;font-size: 20px;font-weight: bold;")
        self.bdoa1.clicked.connect(self.doa1)

        self.bdoa2 = QPushButton("Kebaikan",self)
        self.bdoa2.move(200,170)
        self.bdoa2.resize(150,50)
        self.bdoa2.setStyleSheet("font-family: arial;font-size: 20px;font-weight: bold;")
        self.bdoa2.clicked.connect(self.doa2)

        self.bdoa3 = QPushButton("Selamat",self)
        self.bdoa3.move(200,240)
        self.bdoa3.resize(150,50)
        self.bdoa3.setStyleSheet("font-family: arial;font-size: 20px;font-weight: bold;")
        self.bdoa3.clicked.connect(self.doa3)

        self.bdoa4 = QPushButton("Ampunan",self)
        self.bdoa4.move(200,310)
        self.bdoa4.resize(150,50)
        self.bdoa4.setStyleSheet("font-family: arial;font-size: 20px;font-weight: bold;")
        self.bdoa4.clicked.connect(self.doa4)

        self.ddoa1 = ddoa1()
        self.ddoa2 = ddoa2()
        self.ddoa3 = ddoa3()
        self.ddoa4 = ddoa4()

    def doa1(self):
        self.ddoa1.doa1displayon()

    def doa2(self):
        self.ddoa2.doa2displayon()

    def doa3(self):
        self.ddoa3.doa3displayon()
    
    def doa4(self):
        self.ddoa4.doa4displayon()

    def kembalikan(Self):
        widget.setWindowTitle("HOME")
        widget.setFixedWidth(540)
        widget.setFixedHeight(540)
        widget.setCurrentIndex(widget.currentIndex()-3)

class ddoa1(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Mensyukuri nikmat Allah SWT")

        keterangan = QLabel("Buka Perbesar",self)
        keterangan.move(20,10)
        keterangan.resize(150,50)
        keterangan.setStyleSheet("font-family: arial;font-size: 15px;font-weight: bold;")

        ketdoa = QLabel("DOA Mensyukuri nikmat Allah SWT",self)
        ketdoa.resize(800,200)
        ketdoa.setStyleSheet("font-family: arial;font-size: 45px;font-weight: bold;")
        ketdoa.move(500,230)

        doa1 = QLabel("بِسْمِ اللهِ الرَّحْمَنِ الرَّحِيْمِ.\n اَلْحَمْدُ ِللهِ رَبِّ الْعَالَمِيْنَ.\n حَمْدًا يُوَافِىْ نِعَمَهُ وَيُكَافِئُ مَزِيْدَهُ.\n"
                        "يَارَبَّنَالَكَ الْحَمْدُ وَلَكَ الشُّكْرُ كَمَا يَنْبَغِىْ لِجَلاَلِ وَجْهِكَ وَعَظِيْمِ سُلْطَانِكَ",self)
        doa1.move(300,20)
        doa1.resize(1000,1000)
        doa1.setStyleSheet("font-family: arial;font-size: 45px;font-weight: bold;")
        

    def doa1displayon(self):
        self.show()

class ddoa2(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Memohon kebaikan Kepada Allah SWT")

        keterangan = QLabel("Buka Perbesar",self)
        keterangan.move(20,10)
        keterangan.resize(150,50)
        keterangan.setStyleSheet("font-family: arial;font-size: 15px;font-weight: bold;")

        ketdoa = QLabel("DOA Memohon kebaikan Allah SWT",self)
        ketdoa.resize(800,100)
        ketdoa.setStyleSheet("font-family: arial;font-size: 45px;font-weight: bold;")
        ketdoa.move(500,230)

        doa1 = QLabel("اَللّٰهُمَّ صَلِّ وَسَلِّمْ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلى آلِ سَيِّدِنَا مُحَمَّدٍ.\n صَلاَةً تُنْجِيْنَابِهَا مِنْ جَمِيْعِ اْلاَهْوَالِ وَاْلآفَاتِ .\n وَتَقْضِىْ لَنَابِهَا جَمِيْعَ الْحَاجَاتِ.وَتُطَهِّرُنَا بِهَا مِنْ جَمِيْعِ السَّيِّئَاتِ. \n "
                        "وَتَرْفَعُنَابِهَا عِنْدَكَ اَعْلَى الدَّرَجَاتِ.\n وَتُبَلِّغُنَا بِهَا اَقْصَى الْغَيَاتِ مِنْ جَمِيْعِ الْخَيْرَاتِ فِى الْحَيَاةِ\n وَبَعْدَ الْمَمَاتِ اِنَّهُ سَمِيْعٌ قَرِيْبٌ مُجِيْبُ الدَّعَوَاتِ وَيَاقَاضِىَ الْحَاجَاتِ.",self)
        doa1.move(300,20)
        doa1.resize(1000,1000)
        doa1.setStyleSheet("font-family: arial;font-size: 45px;font-weight: bold;")
        
    def doa2displayon(self):
        self.show()

class ddoa3(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Memohon Keselamatan Kepada Allah SWT")

        keterangan = QLabel("Buka Perbesar",self)
        keterangan.move(20,10)
        keterangan.resize(150,50)
        keterangan.setStyleSheet("font-family: arial;font-size: 15px;font-weight: bold;")

        ketdoa = QLabel("DOA Memohon Keselamatan Allah SWT",self)
        ketdoa.resize(850,100)
        ketdoa.setStyleSheet("font-family: arial;font-size: 45px;font-weight: bold;")
        ketdoa.move(500,230)

        doa1 = QLabel("اَللّٰهُمَّ اِنَّا نَسْئَلُكَ سَلاَمَةً فِى الدِّيْنِ وَالدُّنْيَا وَاْلآخِرَةِ وَعَافِيَةً فِى الْجَسَدِ وَصِحَّةً فِى الْبَدَنِ\n"
                        "وَزِيَادَةً فِى الْعِلْمِ وَبَرَكَةً فِى الرِّزْقِ وَتَوْبَةً قَبْلَ الْمَوْتِ وَرَحْمَةً عِنْدَ الْمَوْتِ وَمَغْفِرَةً بَعْدَ\n"
                        "الْمَوْتِ. اَللّٰهُمَّ هَوِّنْ عَلَيْنَا فِىْ سَكَرَاتِ الْمَوْتِ وَالنَّجَاةَ مِنَ النَّارِ وَالْعَفْوَ عِنْدَ الْحِسَابِ",self)
        doa1.move(300,20)
        doa1.resize(1250,1000)
        doa1.setStyleSheet("font-family: arial;font-size: 45px;font-weight: bold;")

    def doa3displayon(self):
        self.show()

class ddoa4(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Memohon Ampun Kepada Allah SWT")

        keterangan = QLabel("Buka Perbesar",self)
        keterangan.move(20,10)
        keterangan.resize(150,50)
        keterangan.setStyleSheet("font-family: arial;font-size: 15px;font-weight: bold;")

        ketdoa = QLabel("DOA Memohon Ampun Allah SWT",self)
        ketdoa.resize(850,100)
        ketdoa.setStyleSheet("font-family: arial;font-size: 45px;font-weight: bold;")
        ketdoa.move(550,230)

        doa1 = QLabel("رَبَّنَااغْفِرْلَنَا ذُنُوْبَنَا وَلِوَالِدِيْنَا وَلِمَشَايِخِنَا وَلِمُعَلِّمِيْنَا وَلِمَنْ لَهُ حَقٌّ عَلَيْنَا وَلِمَنْ اَحَبَّ وَاَحْسَنَ\n"
                        "اِلَيْنَا وَلِكَافَّةِ الْمُسْلِمِيْنَ اَجْمَعِيْنَ",self)
        doa1.move(300,20)
        doa1.resize(1250,1000)
        doa1.setStyleSheet("font-family: arial;font-size: 45px;font-weight: bold;")

    def doa4displayon(self):
        self.show()

class AboutUs(QWidget):
    def __init__(self):
        super().__init__()
        self.kembali = QPushButton("Quit",self)
        self.kembali.move(430,500)
        self.kembali.clicked.connect(self.kembalikan)
        linktempel = '<a href={0}>{1}</a>'

        nama = QLabel("Nama : Galih Restu Baihaqi \n"
                        "Dosen : DIAN NEIPA PURNAMASARI,M.Tr.T\n"
                        "Asprak : Ach. Faisol S. Arifin\n"
                        "Pemrograman Desktop 3B 2020/2021\n"
                        "Kelompok 1",self)
        nama.setStyleSheet("font-family: arial;font-size: 25px;font-weight: bold;")
        nama.resize(540,150)
        nama.move(10,10)

        tulisanlink = QLabel("Masukan Dan Saran :",self)
        tulisanlink.setStyleSheet("font-family: arial;font-size: 25px;font-weight: bold;")
        tulisanlink.move(10,270)


        link = QLabel(self)
        link.setStyleSheet("font-family: arial;font-size: 25px;font-weight: bold;")
        link.setOpenExternalLinks(True)
        link.setText(linktempel.format('mailto:190411100177@student.trunojoyo.ac.id', 'Klik Disini'))
        link.move(10,300)


    def kembalikan(Self):
        widget.setWindowTitle("HOME")
        widget.setFixedWidth(540)
        widget.setFixedHeight(540)
        widget.setCurrentIndex(widget.currentIndex()-4)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget=QStackedWidget()
    ma = MenuAwal()
    dt = data()
    ng = ngaji()
    doa = doa()
    au = AboutUs()
    widget.addWidget(ma)
    widget.addWidget(dt)
    widget.addWidget(ng)
    widget.addWidget(doa)
    widget.addWidget(au)
    widget.setFixedWidth(540)
    widget.setFixedHeight(540)
    widget.setWindowTitle("HOME")
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
